import { NgModule } from '@angular/core';
import {
  NbActionsModule,
  NbButtonModule,
  NbCardModule,
  NbCheckboxModule,
  NbDialogModule,
  NbDialogService,
  NbFormFieldModule,
  NbIconModule,
  NbInputModule,
  NbLayoutScrollService,
  NbListModule,
  NbMenuModule,
  NbMenuService,
  NbProgressBarModule,
  NbRadioModule,
  NbSearchModule,
  NbSearchService,
  NbSelectModule,
  NbSidebarModule,
  NbSidebarService,
  NbTabsetModule,
  NbToastrModule,
  NbToastrService,
  NbToggleModule,
  NbTooltipModule,
  NbUserModule,
} from '@nebular/theme';

@NgModule({
  imports: [
    NbSidebarModule,
    NbCardModule,
    NbButtonModule,
    NbTooltipModule,
    NbInputModule,
    NbIconModule,
    NbMenuModule.forRoot(),
    NbTooltipModule,
    NbSearchModule,
    NbActionsModule,
    NbUserModule,
    NbToastrModule.forRoot(),
    NbDialogModule,
    NbDialogModule.forRoot(),
    NbRadioModule,
    NbToggleModule,
    NbCheckboxModule,
    NbFormFieldModule,
    NbProgressBarModule,
    NbSelectModule,
    NbTabsetModule,
    NbListModule,
  ],
  exports: [
    NbSidebarModule,
    NbCardModule,
    NbButtonModule,
    NbTooltipModule,
    NbInputModule,
    NbIconModule,
    NbMenuModule,
    NbTooltipModule,
    NbSearchModule,
    NbActionsModule,
    NbUserModule,
    NbToastrModule,
    NbDialogModule,
    NbRadioModule,
    NbToggleModule,
    NbCheckboxModule,
    NbFormFieldModule,
    NbProgressBarModule,
    NbSelectModule,
    NbTabsetModule,
    NbListModule,
  ],
  providers: [
    NbSidebarService,
    NbMenuService,
    NbSearchService,
    NbToastrService,
    NbDialogService,
    NbLayoutScrollService,
  ],
})
export class NebularModule {}
